

GET http://localhost:8080/ebook/list

###

GET http://localhost:8080/ebook/redis/set/123/ebook
Accept: application/json

###

GET http://localhost:8080/redis/get/15271595887169536
Accept: application/json

###
